name: gd1_a_2401
description: "A new Flutter project."
publish_to: "none"
android:
  applicationId: "com.contohProject.linktree"
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
